FROM registry.cn-hongkong.aliyuncs.com/kaikeba/node:v14.16.0
LABEL maintainer="starkwang starkland@163.com"
LABEL name="node-run"
LABEL version="latest"
WORKDIR /home/app

RUN apk add --no-cache --update curl vim \
  && npm i -g pm2 \
  && pm2 -V && node -v && npm -v && yarn -v \
  && rm -rf /var/cache/apk/* \
  # 设置时区
  && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone
WORKDIR /home/app/
RUN yarn add sharp